language: python
python: 3.6

dist: bionic

arch:
  - amd64
#  - arm64
os: linux


branches:
  only:
    - master
    - dev

addons:
  apt:
    packages:
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - build-essential
      - pkg-config
      - gdb-multiarch
      - git
      - cmake
      - libglib2.0-dev
      - pylint

install:
  - pip3 install -r requirements.txt

before_script:
  - echo "source `pwd`/gef.py" > ~/.gdbinit

script:
  - gdb -q -ex 'gef missing' -ex 'gef help' -ex 'gef config' -ex start -ex continue -ex quit /bin/ls
  - python3 -m pylint -E gef.py
  - make lint
  - make test

notifications:
  email:
    recipients:
      - hugsy+github@blah.cat
    on_success: change
    on_failure: always
