language: python
cache: pip
sudo: required

python:
    - "3.4"

os:
    - linux

branches:
  only:
    - master
    - dev

env:
    - PYTHONPATH=/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages

addons:
  apt:
    packages:
      - gcc
      - gdb

before_script:
  - python3 -m pip install ropper pylint keystone-engine capstone unicorn
  - echo "source `pwd`/gef.py" > ~/.gdbinit

script:
  - gdb -q -ex 'gef help' -ex 'gef config' -ex start -ex continue -ex quit /bin/ls
  - make lint


notifications:
  email:
    recipients:
      - hugsy+github@blah.cat
    on_success: change
    on_failure: always
